### ISSUE TITLE
Cannot Build PSPDFKitUI/PSPDFKitUI.h

### ISSUE THREAD

**Issue by bocodigital** [PSPDFKit/PSPDFKit-Cordova#19]
In Plugin.m

Could not build module 'PSPDFKitUI'
on this line #import <PSPDFKitUI/PSPDFKitUI.h>

**Comment by bocodigital** [comment]
IOS

**Comment by radazzouz** [comment]
I am very sorry about this experience, Bruce!

It's a bit hard to know exactly what's really going on in you project's setup, but it looks like the native PSPDFKit SDK has not been properly integrated into your project. 

Can you please make sure that your Podfile is properly updated as described in step 2 of the [installation guide](https://github.com/PSPDFKit/PSPDFKit-Cordova/tree/master/docs/ios#installation)?

I also tested the integration into a newly created project (https://github.com/PSPDFKit/PSPDFKit-Cordova/tree/master/docs/ios#new-cordova-project) and it worked great! 

Can you please try the suggestions above and let us know if it helps.

**Comment by bocodigital** [comment]
Turns out the developer was using too old a version of Xcode. I will close.
